export const ADD_ANSWER_REQUEST = "ADD_ANSWER_REQUEST"
export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS"
export const ADD_ANSWER_FAILURE = "ADD_ANSWER_FAILURE"

export const VIEW_ANSWERS_REQUEST = "VIEW_ANSWERS_REQUEST"
export const VIEW_ANSWERS_SUCCESS = "VIEW_ANSWERS_SUCCESS"
export const VIEW_ANSWERS_FAILURE = "VIEW_ANSWERS_FAILURE"