export const ADD_CHAT_REQUEST = "ADD_CHAT_REQUEST"
export const ADD_CHAT_SUCCESS = "ADD_CHAT_SUCCESS"
export const ADD_CHAT_FAILURE = "ADD_CHAT_FAILURE"

export const SEE_CHAT_REQUEST = "SEE_CHAT_REQUEST"
export const SEE_CHAT_SUCCESS = "SEE_CHAT_SUCCESS"
export const SEE_CHAT_FAILURE = "SEE_CHAT_FAILURE"