export const ASK_QUESTION_REQUEST = "ASK_QUESTION_REQUEST"
export const ASK_QUESTION_SUCCESS = "ASK_QUESTION_SUCCESS"
export const ASK_QUESTION_FAILURE = "ASK_QUESTION_FAILURE" 

export const ALL_QUESTIONS_REQUEST = "ALL_QUESTIONS_REQUEST"
export const ALL_QUESTIONS_SUCCESS = "ALL_QUESTIONS_SUCCESS"
export const ALL_QUESTIONS_FAILURE = "ALL_QUESTIONS_FAILURE"

export const VIEW_QUESTION_REQUEST = "VIEW_QUESTION_REQUEST"
export const VIEW_QUESTION_SUCCESS = "VIEW_QUESTION_SUCCESS"
export const VIEW_QUESTION_FAILURE = "VIEW_QUESTION_FAILURE"