export const ADD_STAR_QUESTION_REQUEST = "ADD_STAR_QUESTION_REQUEST"
export const ADD_STAR_QUESTION_SUCCESS = "ADD_STAR_QUESTION_SUCCESS"
export const ADD_STAR_QUESTION_FAILURE = "ADD_STAR_QUESTION_FAILURE"

export const SEE_STAR_QUESTION_REQUEST = "SEE_STAR_QUESTION_REQUEST"
export const SEE_STAR_QUESTION_SUCCESS = "SEE_STAR_QUESTION_SUCCESS"
export const SEE_STAR_QUESTION_FAILURE = "SEE_STAR_QUESTION_FAILURE"

export const REMOVE_STAR_QUESTION_REQUEST = "REMOVE_STAR_QUESTION_REQUEST"
export const REMOVE_STAR_QUESTION_SUCCESS = "REMOVE_STAR_QUESTION_SUCCESS"
export const REMOVE_STAR_QUESTION_FAILURE = "REMOVE_STAR_QUESTION_FAILURE"

export const ADD_STAR_ANSWER_REQUEST = "ADD_STAR_ANSWER_REQUEST"
export const ADD_STAR_ANSWER_SUCCESS = "ADD_STAR_ANSWER_SUCCESS"
export const ADD_STAR_ANSWER_FAILURE = "ADD_STAR_ANSWER_FAILURE"

export const SEE_STAR_ANSWER_REQUEST = "SEE_STAR_ANSWER_REQUEST"
export const SEE_STAR_ANSWER_SUCCESS = "SEE_STAR_ANSWER_SUCCESS"
export const SEE_STAR_ANSWER_FAILURE = "SEE_STAR_ANSWER_FAILURE"

export const REMOVE_STAR_ANSWER_REQUEST = "REMOVE_STAR_ANSWER_REQUEST"
export const REMOVE_STAR_ANSWER_SUCCESS = "REMOVE_STAR_ANSWER_SUCCESS"
export const REMOVE_STAR_ANSWER_FAILURE = "REMOVE_STAR_ANSWER_FAILURE"