export const ADD_STAR_REQUEST = "ADD_STAR_REQUEST"
export const ADD_STAR_SUCCESS = "ADD_STAR_SUCCESS"
export const ADD_STAR_FAILURE = "ADD_STAR_FAILURE"

export const SEE_STAR_REQUEST = "SEE_STAR_REQUEST"
export const SEE_STAR_SUCCESS = "SEE_STAR_SUCCESS"
export const SEE_STAR_FAILURE = "SEE_STAR_FAILURE"