export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const VIEW_PROFILE_REQUEST = "VIEW_PROFILE_REQUEST"
export const VIEW_PROFILE_SUCCESS = "VIEW_PROFILE_SUCCESS"
export const VIEW_PROFILE_FAILURE = "VIEW_PROFILE_FAILURE"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

export const SEE_USER_CHATS_REQUEST = "SEE_USER_CHATS_REQUEST"
export const SEE_USER_CHATS_SUCCESS = "SEE_USER_CHATS_SUCCESS"
export const SEE_USER_CHATS_FAILURE = "SEE_USER_CHATS_FAILURE"